import { ApiPropertyOptional } from '@nestjs/swagger';
import { IsBoolean, IsOptional } from 'class-validator';

export class UpdateFarmDeliverySettingsDto {
  @ApiPropertyOptional()
  @IsOptional()
  @IsBoolean()
  canViewCustomerBalance?: boolean;

  @ApiPropertyOptional()
  @IsOptional()
  @IsBoolean()
  canViewBillingSummary?: boolean;

  @ApiPropertyOptional()
  @IsOptional()
  @IsBoolean()
  canRecordCashPayment?: boolean;

  @ApiPropertyOptional()
  @IsOptional()
  @IsBoolean()
  canViewPaymentHistory?: boolean;

  @ApiPropertyOptional()
  @IsOptional()
  @IsBoolean()
  deliveryStaffCanApproveExtraRequests?: boolean;

  @ApiPropertyOptional({
    description:
      'Automatically generate today’s delivery list each morning (IST)',
  })
  @IsOptional()
  @IsBoolean()
  autoGenerateDailyList?: boolean;
}
