import { MigrationInterface, QueryRunner } from 'typeorm';

export class AutoGenerateDailyList1754560000000 implements MigrationInterface {
  name = 'AutoGenerateDailyList1754560000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE "farm_delivery_settings"
        ADD COLUMN IF NOT EXISTS "auto_generate_daily_list" boolean NOT NULL DEFAULT true,
        ADD COLUMN IF NOT EXISTS "last_daily_list_generated_at" TIMESTAMPTZ NULL,
        ADD COLUMN IF NOT EXISTS "last_daily_list_generated_date" date NULL
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE "farm_delivery_settings"
        DROP COLUMN IF EXISTS "last_daily_list_generated_date",
        DROP COLUMN IF EXISTS "last_daily_list_generated_at",
        DROP COLUMN IF EXISTS "auto_generate_daily_list"
    `);
  }
}
