import {
  Column,
  CreateDateColumn,
  Entity,
  JoinColumn,
  OneToOne,
  PrimaryColumn,
  UpdateDateColumn,
} from 'typeorm';
import { Farm } from './farm.entity';

@Entity('farm_delivery_settings')
export class FarmDeliverySettings {
  @PrimaryColumn({ name: 'farm_id', type: 'uuid' })
  farmId!: string;

  @OneToOne(() => Farm, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'farm_id' })
  farm!: Farm;

  @Column({ name: 'can_view_customer_balance', type: 'boolean', default: true })
  canViewCustomerBalance!: boolean;

  @Column({ name: 'can_view_billing_summary', type: 'boolean', default: true })
  canViewBillingSummary!: boolean;

  @Column({ name: 'can_record_cash_payment', type: 'boolean', default: false })
  canRecordCashPayment!: boolean;

  @Column({ name: 'can_view_payment_history', type: 'boolean', default: false })
  canViewPaymentHistory!: boolean;

  @Column({
    name: 'delivery_staff_can_approve_extra_requests',
    type: 'boolean',
    default: false,
  })
  deliveryStaffCanApproveExtraRequests!: boolean;

  /** When true, Nest cron materializes today's list for this farm (IST morning). */
  @Column({ name: 'auto_generate_daily_list', type: 'boolean', default: true })
  autoGenerateDailyList!: boolean;

  @Column({
    name: 'last_daily_list_generated_at',
    type: 'timestamptz',
    nullable: true,
  })
  lastDailyListGeneratedAt!: Date | null;

  /** Calendar date (YYYY-MM-DD) last successfully generated for, in app timezone. */
  @Column({
    name: 'last_daily_list_generated_date',
    type: 'date',
    nullable: true,
  })
  lastDailyListGeneratedDate!: string | null;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt!: Date;
}
