export enum UserRole {
  PLATFORM_OWNER = 'PLATFORM_OWNER',
  FARM_OWNER = 'FARM_OWNER',
  DELIVERY_STAFF = 'DELIVERY_STAFF',
  CUSTOMER = 'CUSTOMER',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  BLOCKED = 'BLOCKED',
}

export enum FarmStatus {
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  BLOCKED = 'BLOCKED',
  REJECTED = 'REJECTED',
  /** Farm-owner-initiated soft close (deactivate / request deletion). */
  CLOSED = 'CLOSED',
}

export enum FarmMemberRole {
  OWNER = 'OWNER',
  DELIVERY_STAFF = 'DELIVERY_STAFF',
}

export enum FarmMemberStatus {
  INVITED = 'INVITED',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  REMOVED = 'REMOVED',
}

export enum CustomerStatus {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  ARCHIVED = 'ARCHIVED',
}

export enum MilkType {
  COW = 'COW',
  BUFFALO = 'BUFFALO',
  MIXED = 'MIXED',
  TONED = 'TONED',
  OTHER = 'OTHER',
}

export enum DeliveryShift {
  MORNING = 'MORNING',
  AFTERNOON = 'AFTERNOON',
  EVENING = 'EVENING',
}

export enum AddressLocationSource {
  CUSTOMER_GPS = 'CUSTOMER_GPS',
  CUSTOMER_MAP_PIN = 'CUSTOMER_MAP_PIN',
  FARM_MAP_PIN = 'FARM_MAP_PIN',
  DELIVERY_STAFF_MAP_PIN = 'DELIVERY_STAFF_MAP_PIN',
  GEOCODED_ADDRESS = 'GEOCODED_ADDRESS',
}

export enum SubscriptionStatus {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  CANCELLED = 'CANCELLED',
}

export enum SubscriptionScheduleType {
  EVERY_DAY = 'EVERY_DAY',
  WEEKDAYS = 'WEEKDAYS',
  /** Every other day from subscription startDate (inclusive). */
  ALTERNATE_DAYS = 'ALTERNATE_DAYS',
  /** Once per week; weekday(s) live in deliveryDays (1=Mon … 7=Sun). */
  WEEKLY = 'WEEKLY',
  CUSTOM = 'CUSTOM',
}

/** ISO weekday numbers 1=Mon … 7=Sun (matches JS getUTCDay remapped). */
export enum Weekday {
  MONDAY = 1,
  TUESDAY = 2,
  WEDNESDAY = 3,
  THURSDAY = 4,
  FRIDAY = 5,
  SATURDAY = 6,
  SUNDAY = 7,
}

export enum DeliveryStatus {
  PENDING = 'PENDING',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  SKIPPED = 'SKIPPED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
  DISPUTED = 'DISPUTED',
}

export enum DeliveryConfirmationStatus {
  NOT_CONFIRMED = 'NOT_CONFIRMED',
  FARM_MARKED_DELIVERED = 'FARM_MARKED_DELIVERED',
  CUSTOMER_CONFIRMED = 'CUSTOMER_CONFIRMED',
  CUSTOMER_REPORTED_NOT_RECEIVED = 'CUSTOMER_REPORTED_NOT_RECEIVED',
  CUSTOMER_REPORTED_WRONG_QUANTITY = 'CUSTOMER_REPORTED_WRONG_QUANTITY',
  CUSTOMER_MARKED_RECEIVED = 'CUSTOMER_MARKED_RECEIVED',
  DISPUTED = 'DISPUTED',
  RESOLVED = 'RESOLVED',
}

export enum DeliveryEventType {
  CREATED = 'CREATED',
  ASSIGNED = 'ASSIGNED',
  CUSTOMER_EXTRA_REQUESTED = 'CUSTOMER_EXTRA_REQUESTED',
  CUSTOMER_EXTRA_CANCELLED = 'CUSTOMER_EXTRA_CANCELLED',
  STAFF_EXTRA_ADDED = 'STAFF_EXTRA_ADDED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  MARKED_DELIVERED = 'MARKED_DELIVERED',
  CUSTOMER_MARKED_RECEIVED = 'CUSTOMER_MARKED_RECEIVED',
  CUSTOMER_CONFIRMED = 'CUSTOMER_CONFIRMED',
  CUSTOMER_REPORTED_NOT_RECEIVED = 'CUSTOMER_REPORTED_NOT_RECEIVED',
  CUSTOMER_REPORTED_WRONG_QUANTITY = 'CUSTOMER_REPORTED_WRONG_QUANTITY',
  SKIPPED = 'SKIPPED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
  DISPUTED = 'DISPUTED',
  RESOLVED = 'RESOLVED',
  REASSIGNED = 'REASSIGNED',
  DELIVERY_EDITED = 'DELIVERY_EDITED',
  EDIT_REVIEW_CONFIRMED = 'EDIT_REVIEW_CONFIRMED',
  EDIT_REVIEW_FLAGGED = 'EDIT_REVIEW_FLAGGED',
}

export enum DeliveryEditReviewStatus {
  NOT_REQUIRED = 'NOT_REQUIRED',
  PENDING_REVIEW = 'PENDING_REVIEW',
  CONFIRMED = 'CONFIRMED',
  FLAGGED = 'FLAGGED',
}

export enum DeliveryEditReason {
  ENTERED_WRONG_QUANTITY = 'ENTERED_WRONG_QUANTITY',
  CUSTOMER_CORRECTED_QUANTITY = 'CUSTOMER_CORRECTED_QUANTITY',
  EXTRA_MILK_ENTERED_INCORRECTLY = 'EXTRA_MILK_ENTERED_INCORRECTLY',
  OTHER = 'OTHER',
}

export enum ExtraRequestStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  FULFILLED = 'FULFILLED',
}

export enum DeliveryIssueType {
  NOT_RECEIVED = 'NOT_RECEIVED',
  WRONG_QUANTITY = 'WRONG_QUANTITY',
  WRONG_PRODUCT = 'WRONG_PRODUCT',
  QUALITY_ISSUE = 'QUALITY_ISSUE',
  OTHER = 'OTHER',
}

export enum DeliveryIssueStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESOLVED = 'RESOLVED',
  DISMISSED = 'DISMISSED',
}

export enum ReviewStatus {
  PUBLISHED = 'PUBLISHED',
  HIDDEN = 'HIDDEN',
  REPORTED = 'REPORTED',
  REMOVED = 'REMOVED',
}

export enum NotificationType {
  EXTRA_MILK_REQUESTED = 'EXTRA_MILK_REQUESTED',
  EXTRA_REQUEST_ACCEPTED = 'EXTRA_REQUEST_ACCEPTED',
  EXTRA_REQUEST_REJECTED = 'EXTRA_REQUEST_REJECTED',
  DELIVERY_ASSIGNED = 'DELIVERY_ASSIGNED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  MILK_DELIVERED = 'MILK_DELIVERED',
  CUSTOMER_MARKED_RECEIVED = 'CUSTOMER_MARKED_RECEIVED',
  CUSTOMER_CONFIRMED_DELIVERY = 'CUSTOMER_CONFIRMED_DELIVERY',
  CUSTOMER_REPORTED_NOT_RECEIVED = 'CUSTOMER_REPORTED_NOT_RECEIVED',
  WRONG_QUANTITY_REPORTED = 'WRONG_QUANTITY_REPORTED',
  DELIVERY_ISSUE_RESOLVED = 'DELIVERY_ISSUE_RESOLVED',
  CASH_PAYMENT_RECORDED = 'CASH_PAYMENT_RECORDED',
  CASH_PAYMENT_CLAIMED = 'CASH_PAYMENT_CLAIMED',
  CASH_PAYMENT_CONFIRMED = 'CASH_PAYMENT_CONFIRMED',
  CASH_PAYMENT_REJECTED = 'CASH_PAYMENT_REJECTED',
  CUSTOMER_REVIEW_ADDED = 'CUSTOMER_REVIEW_ADDED',
  CUSTOMER_REVIEW_REPORTED = 'CUSTOMER_REVIEW_REPORTED',
  DELIVERY_EDITED = 'DELIVERY_EDITED',
  DELIVERY_EXTRA_CHANGED = 'DELIVERY_EXTRA_CHANGED',
  DELIVERY_QUANTITY_CHANGED = 'DELIVERY_QUANTITY_CHANGED',
  DELIVERY_AMOUNT_CHANGED = 'DELIVERY_AMOUNT_CHANGED',
  DELIVERY_EDIT_CONFIRMED = 'DELIVERY_EDIT_CONFIRMED',
  DELIVERY_EDIT_FLAGGED = 'DELIVERY_EDIT_FLAGGED',
  SERVICE_REQUEST_CREATED = 'SERVICE_REQUEST_CREATED',
  SERVICE_REQUEST_ACCEPTED = 'SERVICE_REQUEST_ACCEPTED',
  SERVICE_REQUEST_CANCELLED = 'SERVICE_REQUEST_CANCELLED',
  PRODUCT_RATE_CHANGED = 'PRODUCT_RATE_CHANGED',
  CUSTOMER_NO_MILK_TODAY = 'CUSTOMER_NO_MILK_TODAY',
  FARM_NO_DELIVERY_TODAY = 'FARM_NO_DELIVERY_TODAY',
  GENERIC = 'GENERIC',
}

export enum PushDeliveryStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  SKIPPED_NOT_CONFIGURED = 'SKIPPED_NOT_CONFIGURED',
  FAILED = 'FAILED',
  NO_DEVICE = 'NO_DEVICE',
}

export enum CashPaymentPurpose {
  BILL_PAYMENT = 'BILL_PAYMENT',
  ADVANCE_PAYMENT = 'ADVANCE_PAYMENT',
  DAIRY_ORDER_PAYMENT = 'DAIRY_ORDER_PAYMENT',
}

export enum BillStatus {
  DRAFT = 'DRAFT',
  ISSUED = 'ISSUED',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  VOID = 'VOID',
}

export enum BillItemType {
  MILK_DELIVERY = 'MILK_DELIVERY',
  PREVIOUS_BALANCE = 'PREVIOUS_BALANCE',
  DISCOUNT = 'DISCOUNT',
  ADJUSTMENT = 'ADJUSTMENT',
}

export enum PaymentMethod {
  CASH = 'CASH',
  UPI = 'UPI',
  BANK_TRANSFER = 'BANK_TRANSFER',
  OTHER = 'OTHER',
}

export enum PaymentStatus {
  PENDING_CONFIRMATION = 'PENDING_CONFIRMATION',
  CONFIRMED = 'CONFIRMED',
  REJECTED = 'REJECTED',
}

export enum ServiceAreaStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

/** farm_customer_connections.status */
export enum ConnectionStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  BLOCKED = 'BLOCKED',
  CLOSED = 'CLOSED',
}

/** customer_service_requests.status */
export enum ServiceRequestStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

/**
 * Shared status set for farm_customer_invitations and
 * farm_member_invitations (both are time-bound outbound invites).
 */
export enum InvitationStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

/** delivery_assignments.status */
export enum DeliveryAssignmentStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}
